new_page_extension: md
auto_deploy: false
admin_path:
webhook_url:
sections:
  - type: heading
    label: Content

  - type: directory
    path: content/projects
    label: projects
    create: documents
    match: "**/*"
    new_doc_ext: md
    templates:
      - blog-post

  - type: directory
    path: content/experiences
    label: experiences
    create: documents
    match: "**/*"
    new_doc_ext: md
    templates:
      - experiences

  - type: directory
    path: content/qualifications
    label: qualifications
    create: documents
    match: "**/*"
    new_doc_ext: md
    templates:
      - qualifications
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: public
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run develop
